# web
- hosts: web
  sudo: yes

  tasks:

  - name: install nginx
    apt: name=nginx state=installed

#  - name: write our nginx.conf
#    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
#    notify: restart nginx

#  - name: write our /etc/nginx/sites-available/default
#    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
#    notify: restart nginx

#  - name: deploy website content
#    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted
